version: "3.8"

services:
  streamlit-app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - CLOCKIFY_API_KEY=${CLOCKIFY_API_KEY}
    restart: unless-stopped
